import type { Metadata } from "next";
import { Cormorant, Work_Sans } from "next/font/google";
import "./globals.css";

const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${workSans.variable} ${cormorant.variable} antialiased`}
    >
      <body className="font-sans bg-background text-foreground">
        <div id="backdrop-hook"></div>
        <div id="modal-hook"></div>
        <div className="min-h-[calc(100vh-16rem)]">
          <main className="w-full mx-auto my-12 px-2 max-w-225">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
