import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body>
        <div id="backdrop-hook"></div>
        <div id="modal-hook"></div>
        <div className="min-h-[calc(100vh-16rem)]">
          <main className="w-full mx-auto my-12 px-2 max-w-225">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
